<?php
/***************************************/
/***************************************/
/*    THIS IS AN AUTOGENERATED FILE    */
/*        DO NOT EDIT THIS FILE        */
/*   YOUR CHANGES WILL NOT BE SAVED    */
/***************************************/
/***************************************/

/**
    Please, contact Pressidium's support department, if you need to make
    changes to the settings in this file.

    Config file belongs to msautuff of account u1329 on the production environment
    Script generated on Mon Jun  5 06:47:30 2017
*/

$redis_server=array('host' => '127.0.0.1', 'port' => 22129);



/* cache settings, user can edit them using https://cp.pressidium.com/ */
/* production cache settings */
$pressidium_cache_level = "A";
$pressidium_plugins_exclude_from_cache = array();
$pressidium_exclude_from_cache=array();
$pressidium_exclude_from_cache[] ="^/wp-json/";
$pressidium_custom_rewrites=array();
$pressidium_custom_ttl_for_urls=array();
/* these values can/will be overwritten by the ones defined in wp-config.php */
if ( !defined('WP_CACHE') ) {
    define('WP_CACHE', true);
}
// debug options
if ( !defined('WP_DEBUG') ) {
    define('WP_DEBUG', false);
}
if ( !defined('WP_DEBUG_LOG') ) {
    define( 'WP_DEBUG_LOG', false );
}
if ( !defined('WP_DEBUG_DISPLAY') ) {
    define( 'WP_DEBUG_DISPLAY', false);
}
// editor
if ( !defined('DISALLOW_FILE_EDIT') ) {
    define('DISALLOW_FILE_EDIT', true);
}


/* these values are not meant to be changed by the user */

define('WP_NINUKIS_IP', 'c32.cluster.pressidium.com');
define('WP_NINUKIS_WP_NAME', 'msautuff');
define('WP_NINUKIS_ACCOUNT', 'u1329');
define('WP_NINUKIS_HOME', '/wp-storage/c32');
define('WP_NINUKIS_CLUSTER', 'c32');
define('WP_NINUKIS_PUBLIC_API_KEY', 'f37fd1e3db98129de8d651b6d9651208');
define('WP_NINUKIS_SECRET_API_KEY', 'JDUkcm91bmRzPTUzNTAwMCQweWhuUkxVTWFQNWpQZGtRJEp4bElJZlVqOHBSWXNxR0NpL2VXZXdXZHNZbTA4WkJaclR2UDhFSjUxMzk');
define('WP_NINUKIS_API_URL', 'http://c3-api.pressidium.com/restricted/api/v1.0');
define('WP_NINUKIS_SMACKER_BASE', 'http://c3-smacker.pressidium.com/index.php?file=');
define('WP_NINUKIS_SALT', 'kUErnqF');
define('WP_NINUKIS_SFTP_HOST', 'sftp.msautuff.onpressidium.com');
define('WP_NINUKIS_SFTP_PORT', '11532');
define('PRESSIDIUM_FORCE_LOGIN_PROTECTION', true);
define('PRESSIDIUM_FORCE_STRONG_PASSWORDS', true);
define('PRESSIDIUM_DISABLE_MENU', false);
define('WP_AUTO_UPDATE_CORE', false);
define('FS_METHOD', 'direct' );
define('FS_CHMOD_DIR', 0775 );
define('FS_CHMOD_FILE', 0664 );
define('WP_POST_REVISIONS',5);
define('EMPTY_TRASH_DAYS', 7);
define('AUTOSAVE_INTERVAL', 180 ); // Seconds
define('DISABLE_WP_CRON', true);
define('WP_MEMORY_LIMIT', '256M');
define('WP_MAX_MEMORY_LIMIT', '256M');
